apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: demo-app
spec:
  id: demo-app
  parameters:
    namespace: production
    image: docker.io/syedanees85/demo-app:0.0.0
    host: demo-app.54.211.11.133.nip.io
  compositionSelector:
    matchLabels:
      type: backend-db-local
