---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  annotations:
    gitHubOrg: anees-mscs-org
    gitHubRepo: demo-app
  name: demo-app
spec:
  id: demo-app
  compositionSelector:
    matchLabels:
      type: backend-db-aws
      location: local
  parameters:
    namespace: development
    image: docker.io/syedanees85/demo-app:latest
    port: 8080
    host: demo-app.54.211.11.133.nip.io
    db:
      version: "13"
      size: medium
